### PR TITLE
Imp Stacks ques added 

### PR DESCRIPTION
**Pull request by aditya2548**

### CODE REVIEW

**Comment by aditya2548** [comment]
Added important questions on Stacks from interviewbit. Please merge

**Comment by devanshjsr** [comment]
Let me review once.

**Comment by aditya2548** [comment]
Jyaada akar bakar nahi -_-

**Comment by Blazer-007** [comment]
@aditya2548  Please provide commit message in good and proper format

**Comment by aditya2548** [comment]
Please go and buy a new laptop charger (and stabiliser)

**Comment by devanshjsr** [comment]
@aditya2548 please comment only relevant information to smoothen the process of collaboration.

**Pull request merged**
